Update build.yml
Перебрался сборку для rn9pro

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -3,21 +3,23 @@ on:
   push:
   workflow_dispatch:
   schedule:
-    - cron: '0 0 * * 5' # Run every friday at midnight
+    - cron: '0 0 * * 5'
 
 env:
   KERNEL_BRANCH: 6.12.1
 
 jobs:
   build-image:
-    strategy:
-      matrix:
-        version: ["default"]
-
     runs-on: ubuntu-latest
     steps:
       - name: Check out build configurations
         uses: actions/checkout@v4
+
+      - name: Install System Dependencies
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y qemu-user-static jq
+          sudo systemctl restart systemd-binfmt.service || true
 
       - name: Substitute placeholders in configs
         run: |
@@ -38,24 +40,22 @@ jobs:
           DEFAULT_BRANCH=$(git remote show sm7125 | awk '/HEAD branch/ {print $NF}')
           git fetch sm7125 $DEFAULT_BRANCH
           git reset --hard sm7125/$DEFAULT_BRANCH
+          # Исправляет конфликты версий (exit code 12)
+          pmbootstrap index
 
       - name: Check kernel branch
-        if: matrix.version == 'default'
         run: |
-          DEFAULT_BRANCH=$(curl -s  https://api.github.com/repos/sm7125-mainline/linux | jq -r '.default_branch')
-          echo "Default branch is $DEFAULT_BRANCH"
+          DEFAULT_BRANCH=$(curl -s https://api.github.com/repos/sm7125-mainline/linux | jq -r '.default_branch')
           echo "KERNEL_BRANCH=$DEFAULT_BRANCH" >> $GITHUB_ENV
 
       - name: Clone kernel sources
         run: |
           git clone https://github.com/sm7125-mainline/linux.git --single-branch --branch ${{ env.KERNEL_BRANCH }} --depth 1 ./linux
 
-      - name: Choose any SM7125 device in pmbootstrap to build kernel
-        run: |
-          cp xiaomi-curtana.cfg ~/.config/pmbootstrap_v3.cfg
-
       - name: Compile kernel with envkernel
         run: |
+          # Используем joyeuse как базовый конфиг для сборки ядра
+          cp xiaomi-joyeuse.cfg ~/.config/pmbootstrap_v3.cfg
           cd linux
           shopt -s expand_aliases
           source ../pmbootstrap/helpers/envkernel.sh
@@ -67,38 +67,24 @@ jobs:
         run: |
           mkdir out
 
-      - name: Build xiaomi-curtana
-        run: |
-          cp xiaomi-curtana.cfg ~/.config/pmbootstrap_v3.cfg
-          pmbootstrap install --password 147147
-          pmbootstrap export
-          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-curtana.img
-          cp /tmp/postmarketOS-export/xiaomi-miatoll.img out/rootfs-xiaomi-curtana.img
-          sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
-          pmbootstrap export
-          cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-curtana.img
-          xz -T0 -9e -v out/rootfs-xiaomi-curtana.img
-          echo -e "n\nn\ny\n" | pmbootstrap zap
-
-      - name: Upload artifacts
-        uses: actions/upload-artifact@v4
-        with:
-          name: xiaomi-curtana-${{ env.KERNEL_BRANCH }}
-          path: out/*-curtana.img*
-          retention-days: 7
-
       - name: Build xiaomi-joyeuse
         run: |
           cp xiaomi-joyeuse.cfg ~/.config/pmbootstrap_v3.cfg
+          # Предварительная сборка базы, чтобы избежать ошибок инициализации chroot
+          pmbootstrap build postmarketos-base-systemd --arch aarch64
+          
+          # Сборка для tianma
           pmbootstrap install --password 147147
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-tianma-joyeuse.img
           cp /tmp/postmarketOS-export/xiaomi-miatoll.img out/rootfs-xiaomi-joyeuse.img
+          
+          # Сборка для huaxing
           sed -i 's/tianma/huaxing/g' ~/.config/pmbootstrap_v3.cfg
           pmbootstrap export
           cp /tmp/postmarketOS-export/boot.img out/boot-xiaomi-huaxing-joyeuse.img
+          
           xz -T0 -9e -v out/rootfs-xiaomi-joyeuse.img
-          echo -e "n\nn\ny\n" | pmbootstrap zap
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
@@ -106,3 +92,4 @@ jobs:
           name: xiaomi-joyeuse-${{ env.KERNEL_BRANCH }}
           path: out/*-joyeuse.img*
           retention-days: 7
+
